services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - vendee-cinema
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:8
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - vendee-cinema
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vendee-cinema

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432?sslmode=disable'
    ports:
      - 9187:9187
    networks:
      - vendee-cinema
    depends_on:
      - postgres

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter
    restart: always
    command: -redis.addr=redis://:${REDIS_PASSWORD}@redis:6379
    ports:
      - 9121:9121
    networks:
      - vendee-cinema
    depends_on:
      - redis

  rabbitmq-exporter:
    container_name: rabbitmq-exporter
    image: kbudde/rabbitmq-exporter
    restart: always
    environment:
      RABBIT_URL: 'http://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:15672'
    ports:
      - 9419:9419
    networks:
      - vendee-cinema
    depends_on:
      - rabbitmq

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - vendee-cinema

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - vendee-cinema

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  vendee-cinema:
    external: true
